### ISSUE TITLE
RewriteRule w .htaccess nie obsługuje dwucyfrowych numerów rund

### ISSUE THREAD

**Issue by michzimny** [michzimny/teamy-diff-deals#1]
Obecnie w RewriteRule numer rundy jest dopasowywany do wyrażenia "\d" zamiast nasuwającego się "\d+". W przypadku, gdy prefiks turnieju kończy się cyfrą, program nie ma jak rozstrzygnąć, czy ta cyfra należy do prefiksu czy numeru rundy. 

Na razie wybrałem mniejsze zło - przyjąłem, że numer rundy jest jednocyfrowy.

**Comment by emkael** [comment]
"Mniejszym złem" chyba jednak jest zakładanie, że prefiks nie kończy się cyfrą (łatwo wymusić, a rozwiązanie działa zawsze). Poza tym, że w bieżących rozgrywkach tak jest... :)

**Comment by michzimny** [comment]
W bieżących rozgrywkach właśnie prefiksy kończą się cyframi, więc teraz mniejszym złem jest przyjęcie, że rund jest mało :)

**Comment by emkael** [comment]
W szczególności tak. W ogólności - podoba mi się nawyk Artura, który prefiksy plików turnieju zawsze kończy podkreślnikiem.

**Comment by michzimny** [comment]
Dla mnie podkreślnik brzydko wygląda w URL-u :P

**Comment by emkael** [comment]
To myślnik, skoro i tak są myślniki w URLach.
