### ISSUE TITLE
Ukrywanie zapisów w kontrolkach

### ISSUE THREAD

**Issue by emkael** [michzimny/teamy-diff-deals#13]
Być może do zrealizowania poprzez zapisywanie informacji o tym, które rozdania są ukrywane/wyświetlane, do zewnętrznego źródła danych (cache'a), z którego mogłyby wspólnie korzystać skrypty protokołów i kontrolek.

**Comment by michzimny** [comment]
Przydadzą się do tego pewnie kody ukrywacza, które już parsują kontrolkę meczową. Weźmiesz sobie z ftp?

**Comment by emkael** [comment]
Wezmę, wezmę.
