### ISSUE TITLE
Protocol::output szuka <h4> którego nie ma

### ISSUE THREAD

**Issue by michzimny** [michzimny/teamy-diff-deals#16]
W ekstraklasie nie działały protokoły przez tego ifa:
https://github.com/michzimny/teamy-diff-deals/blob/f834b2e556f657d990cb3751a503b2d055972dc0/tdd/tdd-bootstrap.php#L118

Zakomentowałem tego ifa z całym jego body i zaczęło działać.

W oryginalnym protokole nie ma `<h4>`, mimo że zapisy są (czyli sędzia odhaczył "don't send boards"), a skrypt go szuka i w związku z brakiem drukuje oryginalny html.

Co za h4 jest tu oczekiwany i dlaczego nie ma go w ekstraklasie?

@emkael

**Comment by emkael** [comment]
Komentarz linia wyżej :)

To jest `<h4>`, który oznacza, że w oryginalnym HTMLu jest jakikolwiek rozkład, który będzie rozkładem domyślnym w przypadku niepodpięcia do jakiegoś stołu rozkładów.

Można ten warunek *chyba* zdjąć, ale zerknę jeszcze, czy dalszy kod, który dzieli rozkłady na poszczególne stoły nie psuje się, zakładając, że istnieje domyślny rozkład.

**Comment by michzimny** [comment]
Przeoczyłem kiedy to wprowadziłeś, ale ja w oryginalnej wersji zakładałem, że może nie istnieć oryginalny rozkład, bo wręcz kazałem wszystkim sędziom nie podpinać domyślnego.

**Comment by emkael** [comment]
Efekt wyrzucenia tego warunku jest taki: http://www.pzbs.pl/wyniki/liga/liga2018-19/ekstraklasa/po1a1b-37.html

`Fatal error: Call to a member function find() on a non-object in tdd-bootstrap.php on line 165`

**Comment by michzimny** [comment]
Czyli zostało nam ok. 18 rozdań, aby rozwiązać problem :D

**Comment by emkael** [comment]
Już naprawiłem, zaraz wrzucę.

**Comment by emkael** [comment]
I sypie się tylko pusta ramka, sprzed wysłania pierwszego zapisu.
