### ISSUE TITLE
Widać zapis mimo że chyba nie powinno być widać

### ISSUE THREAD

**Issue by michzimny** [michzimny/teamy-diff-deals#17]
Patrz załącznik. Czy to oczekiwane?

@emkael 
<img width="222" alt="capture" src="https://user-images.githubusercontent.com/1483196/52140011-f10edb80-2651-11e9-9f85-77cd45598780.PNG">

**Comment by emkael** [comment]
Nieoczekiwane, pewnie o jakiejś klasie komórki do ukrycia zapomniałem

**Comment by emkael** [comment]
Linia 103 w `tdd-bootstrap.php`
