### ISSUE TITLE
Kompatybilność z PHP 5.2.x

### ISSUE THREAD

**Issue by emkael** [michzimny/teamy-diff-deals#20]
Na warsbrydz.pl jest antyczna wersja PHP.

Już linia nr 9 tdd-bootstrap.php się sypie, bo deklaracja stałych przez `const` poza klasą weszła dopiero w PHP 5.3.

Przejmujemy się kompatybilnością z PHP 5.2, czy wprost przeciwnie?

**Comment by michzimny** [comment]
Wprost przeciwnie? :)

Może niższy koszt ma supportowanie warsbrydza, jak się dogadać z hostingiem, żeby zrobili upgrade?

**Comment by emkael** [comment]
Wygląda na to, że problemy skończyły się na:
 - zamianie `const` na `define()`
 - zamianie `static::` na `self::`

Poprawki są nieinwazyjne i kompatybilne z główną linią, więc wrzucę je w wolnej chwili.
