### ISSUE TITLE
Numer stołu w przypadku ręczników

### ISSUE THREAD

**Issue by michzimny** [michzimny/teamy-diff-deals#22]
http://pzbs.pl/wyniki/liga/liga2018-19/wspolne/skorpo41t2-5.htm

Stół 2 gra, w stół 1 ma w tym segmencie ręcznik. Na FTP był plik starpo4-r1-t2-b49.pbn i nie było rozkładów w kontrolce. Zmieniliśmy nazwę pliku z t2 na t1 i się pojawiły. 

To chyba nieintuicyjne?

@emkael

**Comment by emkael** [comment]
Widzę na FTP pliki: skorpo4-r1-t1-b1.pbn, skorpo4-r1-t1-b25.pbn oraz skorpo4-r1-t2-b1.pbn, skorpo4-r1-t2-b25.pbn i skorpo4-r1-t2-b49.pbn - i pokazuje się rozkład dla stołu nr 2.
Analogicznie jest w starpo4*

**Comment by emkael** [comment]
> **star**po4-r1-t2-b49.pbn

To już wiem, czemu nie mieliście rozkładów i czemu zniknęły mnie.

To był MÓJ plik, a Wy nie wrzuciliście wcześniej w ogóle :)
Dlatego nie mieliście rozkładów i dlatego ja musiałem sobie przed chwilą je wrzucić ponownie.

**Comment by michzimny** [comment]
dziwna sprawa :P
