### ISSUE TITLE
Nieużywany parametr

### ISSUE THREAD

**Issue by michzimny** [michzimny/teamy-diff-deals#25]
https://github.com/michzimny/teamy-diff-deals/blob/fa37ab6a858fe75161bcad77cc863ccb73712983/tdd/tdd-bootstrap.php#L555

Ta linia kodu używa pola klasy __dbFile, podczas gdy metoda ma parametr dbFile, który wygląda na nieużywany. Czy wszystko tu jest ok?

@emkael ?

**Comment by emkael** [comment]
Owszem, jest nieużywany, do usunięcia.
W 030773982c27583086bf93182b122fc5cefb8ad7 opakowałem bazę rozdań w klasę i parametr tej metody wywędrował do jej (klasy) konstruktora, widocznie rozdwajając się przy okazji.
