### ISSUE TITLE
URL z query zwraca błąd

### ISSUE THREAD

**Issue by michzimny** [michzimny/teamy-diff-deals#31]
Np. 
po adresem https://www.pzbs.pl/wyniki/liga/liga2019-20/2liga/nw/nwpo11t1-1.html?fbclid=1
dostaję:
> This script cannot be called directly!

Problemem jest query, doklejane np. przy przesyłaniu URL-i przez facebooka. 

Może należałoby wykryć, że jest query i przekierować na URL bez query?

@emkael ?

**Comment by emkael** [comment]
Dziwne, ktoś podaje linki do pojedynczych ramek na Facebooku? :P

Ten warunek działa na `$_SERVER['REQUEST_URI']`, trzeba z niego w obu plikach wyciąć query string, np. tak: https://stackoverflow.com/a/6975045

**Comment by emkael** [comment]
W przypadku `tdd-scoresheet.php` o tyle istotne, że zmienna `$html_filename` brana z `REQUEST_URI` jest później używana jako ścieżka do pliku.

**Comment by michzimny** [comment]
Rzeczywiście, to problem tylko przy pojedynczych ramkach, to chyba traci na pilności, skoro tylko Zimny będzie miał problem :P
